### PR TITLE
Ui

### PR DESCRIPTION
**Pull request by 100862367**
screenshot_20180917-205356_finderkeeper
screenshot_20180917-205358_finderkeeper
screenshot_20180917-205402_finderkeeper
screenshot_20180917-205416_finderkeeper
screenshot_20180917-205419_finderkeeper
screenshot_20180917-205425_finderkeeper
screenshot_20180917-210151_finderkeeper
screenshot_20180917-210156_finderkeeper
screenshot_20180917-212849_finderkeeper
screenshot_20180917-212852_finderkeeper

- Changed the menu scene background and added an option button
- Change the overall UI in map scene
- UIs on the device is exactly the same as what you see on unity editor
- Buttons will be highlighted when press on
- Changed time format into 00:00
- Time now stop at 05:00
- Items are displayed as 0/5
- Changed background for End scene
- Added a Home button which bring player back to the menu scene

### CODE REVIEW

**Comment by LMDyer** [comment]
Please add some screenshots of the UI changes

**Comment by Fez15** [comment]
To be honest I think you should change the font of "finder seeker" and "collect". 
Also I remember Val saying that buttons should have some sort of line around it to show its actually a button.
Other than that it looks great

**Comment by LMDyer** [comment]
> To be honest I think you should change the font of "finder seeker" and "collect".
> Also I remember Val saying that buttons should have some sort of line around it to show its actually a button.
> Other than that it looks great

I agree with the buttons, but I think this branch is a good start to UI changes. Should we have the buttons changed here, or in another branch do you reckon?

**Comment by 100862367** [comment]
> 
> 
> > To be honest I think you should change the font of "finder seeker" and "collect".
> > Also I remember Val saying that buttons should have some sort of line around it to show its actually a button.
> > Other than that it looks great
> 
> I agree with the buttons, but I think this branch is a good start to UI changes. Should we have the buttons changed here, or in another branch do you reckon?

I've just finished reading the feedback and will implement them tomorrow. 

In regards to the setting button on the title screen, it's really just a placeholder for now. There's also another setting button in the game itself within the menu so we can either merge and delete one of them, or they can have their own separate configurations.
screenshot_20180917-234847_finderkeeper

Also, personally, I felt that having to press the back button to close the menu is rather annoying so I will probably make it such that pressing menu again will close itself. 

For the course screen, we can certainly implement something like "Choose a course" with a list of courses below in the future.
 
As for the buttons, I did try out a few of them but for now they are very ugly so I will play around with them a bit longer.

**Comment by 100862367** [comment]
Here's the update:
screenshot_20180919-043107_finderkeeper
screenshot_20180919-043119_finderkeeper
screenshot_20180919-043138_finderkeeper
screenshot_20180919-043146_finderkeeper
screenshot_20180919-043154_finderkeeper
screenshot_20180919-043200_finderkeeper
screenshot_20180919-043722_finderkeeper
screenshot_20180919-043733_finderkeeper
screenshot_20180919-044547_finderkeeper

**Comment by Jmac92** [comment]
Awesome job with the changes. I'm going to approve these - I just have one little nitpick still with the hamburger pop-out.

If it's easy to change can you add the same amount of padding between the bottom bar and bottom item as there is on the left of the items. The padding between items is fine.

Here's a pic of where I mean : 
screen shot 2018-09-19 at 3 44 13 pm

**Comment by 100862367** [comment]
> 
> 
> Awesome job with the changes. I'm going to approve these - I just have one little nitpick still with the hamburger pop-out.
> 
> If it's easy to change can you add the same amount of padding between the bottom bar and bottom item as there is on the left of the items. The padding between items is fine.
> 
> Here's a pic of where I mean :
> screen shot 2018-09-19 at 3 44 13 pm

Sure thing. Here's the change
menu

**Comment by Jmac92** [comment]
Nailed it. Cheers

**Comment by LMDyer** [comment]
Looks even better, good job! Would it be possible to apply the button styling to the hamburger options? Still happy to approve these changes

**Comment by 100862367** [comment]
> 
> 
> Looks even better, good job! Would it be possible to apply the button styling to the hamburger options? Still happy to approve these changes

Something like this?
capture

**Comment by LMDyer** [comment]
> > Looks even better, good job! Would it be possible to apply the button styling to the hamburger options? Still happy to approve these changes
> 
> Something like this?
> capture

Yeah like that, good work

**Pull request merged**
